server:
  port: 8070
spring:
  application:
    name: netdisc-oauth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'