server:
  port: 8090

spring:
  application:
    name: netdisc-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      globalcors: #解决跨域问题
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOriginPatterns: "*"
            allowCredentials: true
            allowedMethods: "*"

      routes:
        - id: netdisc-filesystem
          uri: lb://netdisc-filesystem
          predicates:
            - Path=/api/files/**,/api/fileFolder/**,/api/search/**
          filters: #排除/api
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar

        - id: netdisc-user
          uri: lb://netdisc-user
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar





